apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scylla-service-monitor
  namespace: scylla
spec:
  jobLabel: "app"
  targetLabels: ["scylla/cluster"]
  podTargetLabels: ["scylla/datacenter"]
  selector:
    matchLabels:
      app: scylla
  endpoints:
    - port: prometheus
      metricRelabelings:
        - sourceLabels: [ scylla_cluster ]
          targetLabel: cluster
          regex: (.*)
          replacement: ${1}
          action: replace
        - sourceLabels: [ scylla_datacenter ]
          targetLabel: dc
          regex: (.*)
          replacement: ${1}
          action: replace
