# config file version
apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  url: http://aprom:9090
  access: proxy
  basicAuth: false
- name: alertmanager
  type: alertmanager
  orgId: 1
  typeLogoUrl: public/img/icn-datasource.svg
  access: proxy
  url: http://-L
  password: 
  user: 
  database: 
  basicAuth: 
  isDefault: 
  jsonData:
    implementation: 'prometheus'
