version: "3.7"

services:
  scylla-manager:
    container_name: scylla-manager
    image: scylladb/scylla-manager:3.2.5
    networks:
      - scylla-network
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    container_name: scylla-manager-db
    image: scylladb/scylla:5.2
    ports:
      - 9041:9042
    command: --smp 1 --memory 1G --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-network
    volumes:
      - ./scylla_manager_db_data:/var/lib/scylla

  scylla-node1:
    container_name: scylla-node1
    build: .
    image: scylladb/scylla-with-agent
    ports:
      - 9042:9042
    restart: always
    # command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    command: --smp 1 --memory 1G --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-network
    volumes:
      - ./scylla_data_node1:/var/lib/scylla

  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - ./minio_data:/data
    networks:
      - scylla-network
    ports:
      - 9001:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

networks:
  scylla-network:
    name: scylla
