apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      game: tictactoe
  template:
    metadata:
      labels:
        game: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: dahankzter/tictactoe:v0.0.1
        ports:
          - containerPort: 5000
        command: ["python"]
        args: ["application.py", "--mode", "local", "--endpoint", "scylla-cluster-client.scylla.svc","--port", "8000"]

---

apiVersion: v1
kind: Service
metadata:
  name: tictactoe
spec:
  type: LoadBalancer
  selector:
    game: tictactoe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
